### ISSUE TITLE
Deux enregistrement consécutif sur la programmation d'un contrôle génère une erreur

### ISSUE THREAD

**Issue by heligonSeb** [pebble-solutions/App-QSE-controle#79]
le primary personnel de nans est a 0 au lieu d'avoir 762 au niveau de son login. Cela l’empêche de voir les contrôles qui lui sont affecté.
![capture_d___e__cran_2023-03-27_a___15 09 13_720](https://user-images.githubusercontent.com/52566459/227969144-b14e3088-80d6-43cf-8db0-428675bd1767.png)

**Comment by Guillaume35** [comment]
<img width="861" alt="Capture d’écran 2023-03-27 à 14 36 07" src="https://user-images.githubusercontent.com/945411/228051629-d3124db7-098f-48c2-bd09-a5d6c7b4f13b.png">

**Comment by Guillaume35** [comment]
```
<br />
<b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to InformationLiaison::setReponses() must be of the type array, null given, called in /app/mkg/motor/information/classe_data.php on line 214 and defined in /app/mkg/motor/information/classe_information_liaison.php:1345
Stack trace:
#0 /app/mkg/motor/information/classe_data.php(214): InformationLiaison-&gt;setReponses()
#1 /app/mkg/motor/_mkg/super_classe.php(2290): Data::collecteAdd()
#2 /app/api/data.php(84): MKG::apiStatic()
#3 /app/api/index.php(104): require('/app/api/data.p...')
#4 {main}
  thrown in <b>/app/mkg/motor/information/classe_information_liaison.php</b> on line <b>1345</b><br />
```

**Comment by Guillaume35** [comment]
Payload de la première requête sur /api/data/POST/collecte
```
id: 70
dc: 2023-03-27 21:57:29
dm: 2023-03-27 22:05:09
commentaire: null
ordre: 0
keygen: 9hdbbdm6paxn
id_edi: null
structure: 2
sess_login_id: 2
corbeille: NON
information__groupe_id: 3
tlc: null
tli: 0
team_id: null
grant_login: null
grant_team: null
grant_public: null
date: 2023-03-27
enqueteur__login_id: 0
enqueteur__structure__personnel_id: 522
rapport: null
document_id: 0
cible__login_id: 0
cible__structure__personnel_id: 522
done: NON
nb_question: 3
nb_reponse: 0
projet_id: 0
ticket_id: 0
result_integer: null
result_float: null
result_var: null
result_enum: null
result_datetime: null
result_text: null
actions: null
date_done: null
previous_id: 0
following_id: null
projet_label: null
enqueteur_nom: MODARD Guillaume
cible_nom: MODARD Guillaume
groupe_lock_timeout: null
formulaire: 3
cible_login: 0
cible_personnel: 522
enqueteur_login: 0
enqueteur_personnel: 522
locked: false
environnement: private
```

Payload de la seconde requête en erreur sur /api/data/POST/collecte
```
id: 70
dc: 2023-03-27 21:57:29
dm: 2023-03-27 22:06:58
commentaire: null
ordre: 0
keygen: 9hdbbdm6paxn
id_edi: null
structure: 2
sess_login_id: 2
corbeille: NON
information__groupe_id: 3
tlc: null
tli: 0
team_id: null
grant_login: null
grant_team: null
grant_public: null
date: 2023-03-27
enqueteur__login_id: 0
enqueteur__structure__personnel_id: 522
rapport: null
document_id: 0
cible__login_id: 0
cible__structure__personnel_id: 522
done: NON
nb_question: 3
nb_reponse: 0
projet_id: 0
ticket_id: 0
result_integer: null
result_float: null
result_var: null
result_enum: null
result_datetime: null
result_text: null
actions: null
date_done: null
previous_id: 0
following_id: null
projet_label: null
enqueteur_nom: MODARD Guillaume
cible_nom: MODARD Guillaume
groupe_lock_timeout: null
formulaire: 3
cible_login: 0
cible_personnel: 522
enqueteur_login: 0
enqueteur_personnel: 522
locked: null
readOnly: false
reponses: null
environnement: private
```

**Comment by Guillaume35** [comment]
Le pb vient de la clé reponses dans le second payload qui déclenche une tentative d'ajout de données sur une valeur null.
